name: Build
on: [push]

jobs:

  TestCreds:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - id: gcp-auth
        name: GCP Authentcation
        uses: google-github-actions/auth@v1
        with:
          service_account: ${{ secrets.GCP_SA }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          cleanup_credentials: true
          create_credentials_file: true
          export_environment_variables: false

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        env:
          GOOGLE_GHA_CREDS_PATH: ${{ steps.gcp-auth.outputs.credentials_file_path }}
        with:
          version: '>= 363.0.0'

      - name: Upload artifacts to GCP
        run: |
          gsutil stat gs://zephyr-samples-builder/index.html

